server:
  port: ${PORT:8080}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    group:
      local-h2db : "local-common,aws"
      local-mariadb : "mariadb,local-common,aws"
    include: # 모듈 추가 시 해당 모듈의 application-h2db.yml 을 사용하기 위해선 include 에 추가해야함
      - aws # AWS 모듈의 application-h2db.yml load
      - jwt
      - h2db-api
---
spring:
  config:
    activate:
      on-profile: local-common
logging:
  level:
    org:
      springframework:
        web: trace