server:
  port: ${PORT:8080}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    group:
      local-h2db : "h2db,local-common"
      local-mariadb : "mariadb,local-common"
    include: # 모듈 추가 시 해당 모듈의 application.yml 을 사용하기 위해선 include 에 추가해야함
#      - aws # AWS 모듈의 application.yml load
---
spring:
  config:
    activate:
      on-profile: local-common
logging:
  level:
    org:
      springframework:
        web: trace
        orm:
          jpa: trace
      hibernate:
        persist:
          entity: trace
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE