server:
  port: ${PORT:8080}
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    group:
      local-h2db : "h2db,local-common"
      local-mariadb : "mariadb,local-common"
---
spring:
  config:
    activate:
      on-profile: local-common
logging:
  level:
    org:
      springframework:
        web: trace
        orm:
          jpa: trace
      hibernate:
        persist:
          entity: trace
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
---
spring:
  config:
    activate:
      on-profile: h2db
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:example;INIT=CREATE SCHEMA IF NOT EXISTS spring;
      username: sa
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3309/spring
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect