spring:
#  config:
#    activate:
#      on-profile: h2db
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:example;INIT=CREATE SCHEMA IF NOT EXISTS spring;
      username: sa
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    "[org.hibernate]": info
