spring:
#  config:
#    activate:
#      on-profile: h2db
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:~/spring;INIT=CREATE SCHEMA IF NOT EXISTS spring;AUTO_SERVER=true;
      username: sa
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
h2:
  tcp-port: 9094
logging:
  level:
    springframework:
      orm:
        jpa: trace
    org:
      hibernate:
        persist:
          entity: trace
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE